version: 2

sphinx:
  fail_on_warning: true
  configuration: doc/conf.py

python:
  install:
    - method: pip
      path: .

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - pip install sphinx-copybutton furo
