version: 2

sphinx:
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - pip install sphinx-copybutton furo
